# Generated by Django 6.1 on 2026-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Joel Ndaba', max_length=150)),
                ('phone', models.CharField(default='+254721952909', max_length=50)),
                ('email', models.EmailField(default='support@iconscomputerschool.co.ke', max_length=254)),
                ('institution', models.CharField(default='Icons Computer School and Cyber', max_length=200)),
                ('office_location', models.CharField(default='Nairobi, Kenya', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
