# Generated by Django 6.1.1 on 2026-09-19 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_platformcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityaudit',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='platformcontact',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='platformcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformcontact',
            name='role',
            field=models.CharField(default='Lead Cybersecurity Coordinator', max_length=150),
        ),
        migrations.AlterField(
            model_name='activityaudit',
            name='activity_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='activityaudit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activityaudit',
            name='risk_score',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='activityaudit',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activityaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformcontact',
            name='email',
            field=models.EmailField(default='joelndaba24@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='platformcontact',
            name='office_location',
            field=models.CharField(default='Icons Cyber Lab, Block B, Room 204', max_length=200),
        ),
        migrations.AlterField(
            model_name='platformcontact',
            name='phone',
            field=models.CharField(default='+25421952909', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='readiness_score',
            field=models.IntegerField(default=0),
        ),
    ]
