# Generated by Django 6.1.1 on 2026-09-19 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_activityaudit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityaudit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='platformcontact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
