# Generated by Django 6.1 on 2026-08-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google', 'Google / Gmail'), ('microsoft', 'Microsoft 365 / Outlook'), ('social', 'Social Media (Instagram / WhatsApp)'), ('bank', 'Banking & Mobile Money (M-Pesa / Cards)')], max_length=50)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('action_text', models.TextField()),
                ('visual_diagram', models.ImageField(blank=True, null=True, upload_to='recovery_visuals/')),
                ('emergency_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['platform', 'step_number'],
            },
        ),
    ]
