# Generated by Django 6.1 on 2026-08-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
    ]
