# Generated by Django 6.1 on 2026-08-30 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmodule',
            options={'ordering': ['module_number']},
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='category',
            field=models.CharField(default='Social Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='estimated_read_time',
            field=models.CharField(default='8 mins', max_length=20),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='learning_images/'),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='module_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='rich_content',
            field=models.TextField(default='', help_text='Full markdown or HTML content for the module lesson.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or direct MP4 video embed link', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'module')},
        ),
    ]
