# Generated by Django 6.1 on 2026-08-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_content', '0002_alter_learningmodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodule',
            name='rich_content',
            field=models.TextField(blank=True, default='', help_text='Full markdown or HTML content for the module lesson.'),
        ),
    ]
