# Generated by Django 6.1.1 on 2026-09-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_content', '0003_alter_learningmodule_rich_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmodule',
            options={},
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='document',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='estimated_read_time',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='module_number',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='rich_content',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='content_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='duration_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='category',
            field=models.CharField(default='Phishing Fundamentals', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_records', to='lms_content.learningmodule'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IncidentGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('threat_category', models.CharField(default='Credential Phishing', max_length=100)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical Priority'), ('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='HIGH', max_length=20)),
                ('summary', models.TextField()),
                ('immediate_steps', models.TextField(help_text='Step-by-step containment instructions separated by newlines or markdown numbers.')),
                ('containment_checklist', models.TextField(blank=True, default='', help_text='Key recovery checks separated by newlines.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
