# Generated by Django 6.1.1 on 2026-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_content', '0004_alter_learningmodule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='modules/documents/'),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='estimated_read_time',
            field=models.CharField(default='10 mins', max_length=50),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='module_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='rich_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='category',
            field=models.CharField(default='Cyber Defense', max_length=100),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
