# Generated by Django 6.1.1 on 2026-09-20 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_number', models.IntegerField(unique=True)),
                ('sender_display_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(default='learner@phishshield.internal', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_time_display', models.CharField(default='Today at 09:15 AM', max_length=100)),
                ('body_html', models.TextField()),
                ('is_phishing', models.BooleanField(default=True)),
                ('threat_category', models.CharField(default='Credential Harvesting', max_length=100)),
                ('detailed_explanation', models.TextField(help_text='Detailed security breakdown explaining RFC indicators, domain analysis, and psychological vectors.')),
                ('key_indicators', models.TextField(help_text='Key bullet points separated by newlines showing exact indicators.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['scenario_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='simulationresult',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='attempted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='user_choice_is_phishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='simulation.simulationscenario'),
        ),
        migrations.AlterUniqueTogether(
            name='simulationresult',
            unique_together={('user', 'scenario')},
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='email',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='time_taken_seconds',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='user_action',
        ),
        migrations.DeleteModel(
            name='SimulationEmail',
        ),
    ]
